config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get  '/users/search', to: 'users#search',       as: 'get_users_search'
  post '/users/search', to: 'users#post_search', as: 'post_users_search'
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
require 'interactors/users'

class UsersController < ApplicationController
  def index
  end

  def search
    render json: users_interactor.where(params[:q], params[:page].to_i), status: :ok
  end

  private

  def users_interactor
    ::Interactors::Users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Select2Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
</head>
<body>

<%= yield %>
<%= yield :javascript %>
</body>
</html>

app/views/users/index.html.erb
<%= select_tag 'select2_name', [], data: {target: 'select2', placeholder: 'Search for a user'} %>

<% content_for :javascript do %>
  <script type='text/javascript'>
    var users = new Select2Demo.Users({getUsers: '<%= post_users_search_path %>'});
    users.init();
  </script>
<% end %>